apiVersion: v1
kind: Secret
metadata:
  name: helix-ehr-secrets
  namespace: helix-ehr
type: Opaque
stringData:
  NEXTAUTH_SECRET: replace-me
  HASURA_GRAPHQL_ADMIN_SECRET: replace-me
  DATABASE_URL: postgres://app-user:replace-me@127.0.0.1:5432/helix_ehr
